language: node_js
node_js:
    - "8"
before_script:
    - yarn bootstrap
    - travis_wait yarn build
    - lerna run ensure-no-project-compile-errors
script:
    - travis_wait lerna run test:ci # running coveralls might take a bit of time
    - lerna run test:ts-versions
after_script:
    - lerna run code-verification
